name: publish_conda

on:
  workflow_dispatch:
    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: publish-to-conda
      uses: MichaelsJP/conda-package-publish-action@v1.1.0
      with:
        subDir: 'conda'
        AnacondaToken: ${{ secrets.ANACONDA_TOKEN }}
        platforms: ''
        override: false
        dry_run: true
